const fetch = require('node-fetch');
const { weatherAPI } = require('../config.json');

async function getWeather(bot, message, [city, country, units]) {
    // fetch normally uses Promises, which use a .catch to handle errors.
    // async/await requires us to use try/catch instead to handle errors.
    try {
        const response = await fetch(`https://api.openweathermap.org/data/2.5/weather?q=${city},${country}&appid=${weatherAPI}&${units}`);
        const json = await response.json(); // Can't unpack (deconstruct) await since it's asynchronously returned

        const { id, name } = json;
        console.log(json);
        console.log(`Got ${name}'s weather data (id: ${id})`);

        //message.channel.send(/* do something with the data*/);
    } catch (err) {
        console.error(err);
    }
}

exports = {
    run: getWeather,
    help: { name: 'weather' }
};